# honestly I might not even use this

version: 2

gomod:
  proxy: true

before:
  hooks:
    - go mod tidy

builds:
  - main: ./main.go
    id: rokon
    flags: -v
    hooks:
       post: go env
    binary: rokon
    ldflags: >
      -X main.version={{.Version}}
      -X main.commit={{.Commit}}
      -X main.date={{.Date}}

    env:
      - CGO_ENABLED=1
      - >-
        {{- if eq .Arch "arm" }}
             CC="arm-linux-gnu-gcc"
             CC_FOR_TARGET="arm-linux-gnu-gcc"
        {{- end }}
        {{- if eq .Arch "arm64" }}
             CC="aarch64-linux-gnu-gcc"
              CC_FOR_TARGET="aarch64-linux-gnu-gcc"
        {{- end }}
        {{- if eq .Arch "arm" }}
             CXX="arm-linux-gnu-g++"
             CXX_FOR_TARGET="arm-linux-gnu-g++"
        {{- end }}
        {{- if eq .Arch "arm64" }}
             CXX="aarch64-linux-gnu-g++"
             CXX_FOR_TARGET="aarch64-linux-gnu-g++"
        {{- end }}

    goos:
      - linux
    goarch:
      # - amd64
      - arm64
      # - arm
    # These binaries should work on Chromebooks and Raspberry Pis, if not, open a bug report.
    # I do not own these devices, so I cannot test them.
    goarm: ["6", "7"]
checksum:
  name_template: "checksums.txt"
  algorithm: sha256
archives:
  - format: binary
    id: rokon
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
  - format_overrides:
      - goos: windows
        format: zip
dockers:
  - image_templates:
    - "ghcr.io/BrycensRanch/Rokon:latest"
    - "ghcr.io/BrycensRanch/Rokon:v{{ .Major }}"
    - "ghcr.io/BrycensRanch/Rokon:v{{ .Major }}.{{ .Minor }}"
    - "ghcr.io/BrycensRanch/Rokon:v{{ .Major }}.{{ .Minor }}.{{ .Patch }}"
    build_flag_templates:
    - "--pull"
    # OCI annotations: https://github.com/opencontainers/image-spec/blob/main/annotations.md
    - "--label=org.opencontainers.image.description={{.Summary}}"
    - "--label=org.opencontainers.image.created={{.Date}}"
    - "--label=org.opencontainers.image.name={{.ProjectName}}"
    - "--label=org.opencontainers.image.revision={{.FullCommit}}"
    - "--label=org.opencontainers.image.version={{.Version}}"
    - "--label=org.opencontainers.image.source={{.GitURL}}"
    - "--label=org.opencontainers.image.url={{.GitURL}}"
release:
  github:
    owner: "BrycensRanch"
    name: "Rokon"
  name_template: "{{.Version}}"
  prerelease: auto
  mode: append
changelog:
  disable: true
