# https://github.com/diamondburned/dissent/blob/main/.github/actions/make-advinst-app/action.yml
name: Setup Docker Environment
description: Sets up QEMU and Docker Buildx and Logs you in to GHCR and adds docker tags

inputs:
  flavor:
    description: flavor of container (prefix)
    default: ""
  tmpfs:
    description: whether or not to put docker on tmpfs
    default: "true"
outputs:
  tags:
    description: 'The output value from the meta step'
    value: ${{ steps.meta.outputs.tags }}  # Replace 'output_name' with your actual output key
  labels:
    description: 'The output value from the meta step'
    value: ${{ steps.meta.outputs.labels }}  # Replace 'output_name' with your actual output key

runs:
  using: composite
  steps:
      - name: Run Docker on tmpfs
        if: inputs.tmpfs == 'true'
        uses: JonasAlfredsson/docker-on-tmpfs@v1
        with:
          tmpfs_size: 5
          swap_size: 4
          swap_location: '/mnt/swapfile'
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          # list of Docker images to use as base name for tags
          images: |
            ghcr.io/${{ github.repository_owner }}/rokon
          # generate Docker tags based on the following events/attribute
          flavor: ${{inputs.flavor}}
          tags: |
            type=edge,branch=master
            type=schedule,pattern=nightly
            type=ref,event=branch
            type=ref,event=tag
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}
