# Action taken from getseabird/seabird:
# https://github.com/getseabird/seabird/blob/fd49c18b0601021a1a4b312a1d1c67b0dc7fe150/.github/workflows/release.yaml#L59

name: Build using MSYS2
description: Build a Go application using MSYS2 and produce a Windows executable.
inputs:
  exe-name:
    description: Name of the executable to produce, must end in .exe
    required: true
  out-path:
    description: Path to the output directory, which contains the executable and all its libraries
    default: result
  msys-system:
    description: MSYS2 system to use
    default: CLANG64
  msys-dependencies:
    description: MSYS2 packages to install
    required: true
  build-tags:
    description: Build tags to use
    default: ""
runs:
  using: composite
  steps:
    - name: Install MSYS2 Environment
      uses: msys2/setup-msys2@v2
      with:
        msystem: ${{inputs.msys-system}}
        update: true
        install: |
          git
          zip
          ${{ inputs.msys-dependencies }}
    - name: Inject msys2 subsystem into env
      shell: msys2 {0}
      run: |
          echo "SUBSYSTEM=${{inputs.msys-system}}" >>${GITHUB_ENV}
    - name: downcase msys2 subsystem input
      shell: msys2 {0}
      run: |
          echo "SUBSYSTEM_L=${SUBSYSTEM,,}" >>${GITHUB_ENV}
    - name: Cache Go modules and build cache
      uses: actions/cache@v4
      with:
          path: |
            C:/a/msys64/var/cache/pacman/pkg             # Cache MSYS2 packages
            C:/a/msys64/${SUBSYSTEM_L}/lib/go                   # Cache Go
            C:/a/msys64/tmp/go-build                     # Cache Go build cache
            ${{ runner.temp }}
            !${{ runner.temp }}\exe
          key: go-msys2-${{ runner.os }}-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            go-msys2-${{ runner.os }}-

    - name: Build
      id: build
      run: |
        export PATH="/${SUBSYSTEM_L}/bin:$PATH"
        rm -rf "${{ runner.temp }}\exe"

        mkdir -p "$OUT_PATH"
        out=$(realpath "$OUT_PATH")

        # Build Rokon
        make TARGET=$EXE_NAME FLAVOR=gtk EXTRALDFLAGS="-s -w -H windowsgui" EXTRAGOFLAGS="-trimpath" BUILDTAGS=$BUILD_TAGS PACKAGEFORMAT=msi PACKAGED=true build

        # copyDLLs copies all required DLLs of the given binaries to the
        # result directory.
        copyDLLs() {
          ldd "$@" \
            | { grep "=> /${SUBSYSTEM_L}/bin/" || true; } \
            | cut -d ' ' -f1 \
            | xargs -I{} cp /${SUBSYSTEM_L}/bin/{} $out/
        }

        # Copy all of the binary's dependencies to the result directory.
        copyDLLs $EXE_NAME
        # countDLLs returns the number of DLLs in the result directory.
        # We use this to recursively copy dependencies until no new DLLs are
        # found.
        countDLLs() {
          find $out -type f -name "*.dll" | wc -l
        }

        # Copy the RSVG and GDBus stuff.
        cp \
          /${SUBSYSTEM_L}/bin/librsvg*.dll \
          /${SUBSYSTEM_L}/bin/gdbus.exe \
          $out
        # Copy DLLs recursively until no new ones are found.
        currentCount=$(countDLLs)
        while true; do
          copyDLLs $out/*.dll

          newCount=$(countDLLs)
          (( newCount == currentCount )) && break
          currentCount=$newCount
        done

        # Copy the GLib schemas and GTK resources.
        (
          cd /${SUBSYSTEM_L}
          cp --parents -r \
            share/glib-2.0/schemas/gschemas.compiled \
            share/gtk-4.0 \
            share/icons \
            lib/gdk-pixbuf-2.0 \
            $out
        )
      shell: msys2 {0}
      env:
        GOROOT: /${SUBSYSTEM_L}/lib/go
        GOPATH: /${SUBSYSTEM_L}
        EXE_NAME: ${{ inputs.exe-name }}
        OUT_PATH: ${{ inputs.out-path }}
        BUILD_TAGS: ${{ inputs.build-tags }}
