name: COPR

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  copr:
    timeout-minutes: 20
    runs-on: ubuntu-24.04
    steps:
      - name: Check out current repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v5
        with:
          go-version: "stable"
      - name: Cancel previous COPR builds
        working-directory: scripts/copr
        env:
          COPR_TOKEN: ${{ secrets.COPR_TOKEN }}
          COPR_LOGIN: ${{ secrets.COPR_LOGIN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          go get
          go run -v .
