name: "Semantic Pull Request"

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

jobs:
  main:
    name: Lint Title
    runs-on: ubuntu-latest
    steps:
      - name: 🤖 is-semantic-release
        uses: sebbo2002/action-is-semantic-pr@main
        with:
          token: ${{ secrets.GH_TOKEN }}
